from database.database import SessionLocal
from database.postulacion_repository import actualizar_postulacion
from agents.logger import log_agent_action

AGENTE = "agente_seguimiento"


def tracker_node(state: dict) -> dict:
    """Updates postulation status to 'En revisión'. No LLM call needed —
    siguiente_paso was already generated by application_node in the same Gemini call."""
    run_id = state.get("run_id", "sin-run-id")
    postulacion_id = state.get("postulacion_id")
    siguiente_paso = state.get("siguiente_paso", "")

    if state.get("error") or not postulacion_id:
        return {"history": [{"agente": AGENTE, "evento": "tracker_omitido"}]}

    log_agent_action(run_id=run_id, agente=AGENTE, evento="seguimiento_iniciado",
                     mensaje=f"Actualizando estado de postulación {postulacion_id} a 'En revisión'.")

    db = SessionLocal()
    try:
        actualizar_postulacion(postulacion_id, {
            "estado": "En revisión",
            "siguiente_paso": siguiente_paso,
        }, db)
    finally:
        db.close()

    log_agent_action(run_id=run_id, agente=AGENTE, evento="seguimiento_completado",
                     mensaje=f"Postulación {postulacion_id} actualizada a 'En revisión'.")

    return {
        "estado": "En revisión",
        "siguiente_paso": siguiente_paso,
        "history": [{"agente": AGENTE, "evento": "seguimiento_completado"}],
    }
